#### Task 1 - Fitbit Dataset

1. Read this dataset in pandas , mysql and mongodb 
2. while creting a table in mysql dont use manual approach to create it  ,always use a automation to create a table in mysql
###### hint - use csvkit library to automate this task and to load a data in bulk in you mysql 
3. convert all the dates avaible in dataset to timestamp format in pandas and in sql you to convert it in date format
4. Find out in this data that how many unique id's we have 
5. which id is one of the active id that you have in whole dataset 
6. how many of them have not logged there activity find out in terms of number of ids 
7. Find out who is the laziest person id that we have in dataset 
8. Explore over an internet that how much calories burn is required for a healthy person and find out how many healthy person we have in our dataset 
9. how many person are not a regular person with respect to activity try to find out those 
10. who is the thired most active person in this dataset find out those in pandas and in sql both . 
11. who is the 5th most laziest person avilable in dataset find it out 
12. what is a totla acumulative calories burn for a person find out

In [1]:
import pandas as pd
import csv
import mysql.connector as connection
import os

In [7]:
conn = connection.connect(host='localhost',user='root',passwd='MSdhoni07',use_pure=True)
cur = conn.cursor()

##read data from csv
csv_data = csv.reader(open('FitBit_data.csv'))
cur.execute('CREATE TABLE sachin12345.FitBit_task (Id FLOAT NOT NULL,ActivityDate DATE NOT NULL,TotalSteps FLOAT NOT NULL,\
TotalDistance FLOAT NOT NULL,TrackerDistance FLOAT NOT NULL,LoggedActivitiesDistance FLOAT NOT NULL,\
VeryActiveDistance FLOAT NOT NULL,ModeratelyActiveDistance FLOAT NOT NULL,LightActiveDistance FLOAT NOT NULL,\
SedentaryActiveDistance FLOAT NOT NULL,VeryActiveMinutes FLOAT NOT NULL,FairlyActiveMinutes FLOAT NOT NULL,\
LightlyActiveMinutes FLOAT NOT NULL,SedentaryMinutes FLOAT NOT NULL,Calories FLOAT NOT NULL)')

header = next(csv_data)
for row in csv_data:
    print(row)
    cur.execute("Insert into sachin12345.FitBit_task(Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,\
    LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,\
    VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories) \
    VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)",row)
conn.commit()
cur.close()
print("All Data Uploaded")

['1503960366', '2016-03-25', '11004', '7.110000134', '7.110000134', '0', '2.569999933', '0.460000008', '4.070000172', '0', '33', '12', '205', '804', '1819']
['1503960366', '2016-03-26', '17609', '11.55000019', '11.55000019', '0', '6.920000076', '0.730000019', '3.910000086', '0', '89', '17', '274', '588', '2154']
['1503960366', '2016-03-27', '12736', '8.529999733', '8.529999733', '0', '4.659999847', '0.159999996', '3.710000038', '0', '56', '5', '268', '605', '1944']
['1503960366', '2016-03-28', '13231', '8.930000305', '8.930000305', '0', '3.190000057', '0.790000021', '4.949999809', '0', '39', '20', '224', '1080', '1932']
['1503960366', '2016-03-29', '12041', '7.849999905', '7.849999905', '0', '2.160000086', '1.090000033', '4.610000134', '0', '28', '28', '243', '763', '1886']
['1503960366', '2016-03-30', '10970', '7.159999847', '7.159999847', '0', '2.359999895', '0.50999999', '4.289999962', '0', '30', '13', '223', '1174', '1820']
['1503960366', '2016-03-31', '12256', '7.860000134', '7.860000134', '0', '2.289999962', '0.49000001', '5.039999962', '0', '33', '12', '239', '820', '1889']
['1503960366', '2016-04-01', '12262', '7.869999886', '7.869999886', '0', '3.319999933', '0.829999983', '3.640000105', '0', '47', '21', '200', '866', '1868']
['1503960366', '2016-04-02', '11248', '7.25', '7.25', '0', '3', '0.449999988', '3.74000001', '0', '40', '11', '244', '636', '1843']
['1503960366', '2016-04-03', '10016', '6.369999886', '6.369999886', '0', '0.910000026', '1.279999971', '4.179999828', '0', '15', '30', '314', '655', '1850']
['1503960366', '2016-04-04', '14557', '9.800000191', '9.800000191', '0', '3.390000105', '0.699999988', '5.690000057', '0', '43', '18', '285', '757', '2030']
['1503960366', '2016-04-05', '14844', '9.729999542', '9.729999542', '0', '2.940000057', '0.75999999', '6.039999962', '0', '36', '18', '341', '736', '2083']
['1503960366', '2016-04-06', '11974', '7.670000076', '7.670000076', '0', '2.039999962', '0.479999989', '5.150000095', '0', '27', '12', '228', '1173', '1861']
['1503960366', '2016-04-07', '10198', '6.440000057', '6.440000057', '0', '1.200000048', '0.790000021', '4.449999809', '0', '17', '20', '195', '1208', '1755']
['1503960366', '2016-04-08', '12521', '7.940000057', '7.940000057', '0', '3.309999943', '0.899999976', '3.74000001', '0', '46', '22', '212', '1160', '1895']
['1503960366', '2016-04-09', '12432', '8.100000381', '8.100000381', '0', '2.589999914', '0.589999974', '4.920000076', '0', '32', '15', '248', '738', '1883']
['1503960366', '2016-04-10', '10057', '6.980000019', '6.980000019', '0', '4', '0.49000001', '2.480000019', '0', '44', '13', '168', '737', '1755']
['1503960366', '2016-04-11', '10990', '7.260000229', '7.260000229', '0', '2.039999962', '0.569999993', '4.650000095', '0', '26', '14', '216', '855', '1811']
['1503960366', '2016-04-12', '224', '0.140000001', '0.140000001', '0', '0', '0', '0.129999995', '0', '0', '0', '9', '32', '50']
['1624580081', '2016-03-25', '1810', '1.179999948', '1.179999948', '0', '0', '0', '1.129999995', '0.01', '0', '0', '121', '1319', '1373']
['1624580081', '2016-03-26', '815', '0.529999971', '0.529999971', '0', '0', '0', '0.529999971', '0', '0', '0', '47', '1393', '1264']
['1624580081', '2016-03-27', '1985', '1.289999962', '1.289999962', '0', '0', '0', '1.279999971', '0.01', '0', '0', '112', '1328', '1350']
['1624580081', '2016-03-28', '1905', '1.24000001', '1.24000001', '0', '0', '0', '1.24000001', '0', '0', '0', '95', '1345', '1342']
['1624580081', '2016-03-29', '1552', '1.00999999', '1.00999999', '0', '0', '0', '1', '0', '0', '0', '66', '1374', '1300']
['1624580081', '2016-03-30', '1675', '1.090000033', '1.090000033', '0', '0', '0', '1.090000033', '0', '0', '0', '84', '1356', '1313']
['1624580081', '2016-03-31', '4506', '2.930000067', '2.930000067', '0', '0.50999999', '0.270000011', '2.150000095', '0.01', '7', '4', '144', '1285', '1498']
['1624580081', '2016-04-01', '9218', '5.989999771', '5.989999771', '0', '0', '0', '5.96999979', '0.01', '0', '0', '221', '1219', '1541']
['1624580081', '2016-04-02', '1556', '1.00999999', '1.00999999', '0', '0', '0', '1.00999999', '0.01', '0', '0', '88', '1352', '1327']
['1624580081', '2016-04-03', '2910', '1.889999986', '1.889999986', '0', '0', '0', '1.879999995', '0.01', '0', '0', '157', '1283', '1452']
['1624580081', '2016-04-04', '18464', '12', '12', '0', '0', '0', '12', '0', '0', '0', '270', '1170', '1574']
['1624580081', '2016-04-05', '1335', '0.870000005', '0.870000005', '0', '0', '0', '0.870000005', '0', '0', '0', '74', '1366', '1308']
['1624580081', '2016-04-06', '1004', '0.649999976', '0.649999976', '0', '0', '0', '0.649999976', '0', '0', '0', '55', '1385', '1276']
['1624580081', '2016-04-07', '1111', '0.720000029', '0.720000029', '0', '0', '0', '0.720000029', '0', '0', '0', '54', '1386', '1278']
['1624580081', '2016-04-08', '6344', '4.119999886', '4.119999886', '0', '0', '0', '4.099999905', '0', '0', '0', '143', '1297', '1409']
['1624580081', '2016-04-09', '3572', '2.319999933', '2.319999933', '0', '0', '0', '2.289999962', '0.029999999', '0', '0', '122', '1318', '1370']
['1624580081', '2016-04-10', '3910', '2.539999962', '2.539999962', '0', '0.469999999', '0.25', '1.809999943', '0.01', '7', '7', '186', '1240', '1555']
['1624580081', '2016-04-11', '10000', '6.5', '6.5', '0', '0', '0', '6.5', '0', '0', '0', '172', '1268', '1469']
['1624580081', '2016-04-12', '6627', '4.309999943', '4.309999943', '0', '0', '0', '4.309999943', '0', '0', '0', '89', '604', '706']
['1644430081', '2016-04-01', '4636', '3.410000086', '3.410000086', '0', '0', '0.779999971', '2.599999905', '0.029999999', '0', '16', '586', '838', '3323']
['1644430081', '2016-04-02', '20237', '14.71000004', '14.71000004', '0', '2.569999933', '6.400000095', '5.730000019', '0.01', '34', '141', '347', '918', '4029']
['1644430081', '2016-04-03', '12912', '9.409999847', '9.409999847', '0', '4.829999924', '0.769999981', '3.789999962', '0.029999999', '59', '16', '283', '1082', '3436']
['1644430081', '2016-04-04', '2819', '2.049999952', '2.049999952', '0', '0.310000002', '0.170000002', '1.559999943', '0.01', '4', '4', '87', '1345', '2444']
['1644430081', '2016-04-05', '9921', '7.210000038', '7.210000038', '0', '0.340000004', '1.519999981', '5.360000134', '0', '5', '35', '219', '1181', '3098']
['1644430081', '2016-04-06', '8046', '5.849999905', '5.849999905', '0', '1.289999962', '2.119999886', '2.450000048', '0', '18', '41', '137', '1244', '2925']
['1644430081', '2016-04-07', '11166', '8.119999886', '8.119999886', '0', '0.209999993', '2.410000086', '5.5', '0', '3', '58', '230', '1149', '3202']
['1644430081', '2016-04-08', '7842', '5.699999809', '5.699999809', '0', '0.479999989', '2.410000086', '2.809999943', '0', '7', '43', '161', '1229', '2928']
['1644430081', '2016-04-09', '13840', '10.06000042', '10.06000042', '0', '1.309999943', '3.720000029', '5.03000021', '0', '18', '81', '192', '1149', '3290']
['1644430081', '2016-04-10', '1329', '0.970000029', '0.970000029', '0', '0', '0', '0.970000029', '0', '0', '0', '35', '207', '489']
['1844505072', '2016-04-01', '6847', '4.53000021', '4.53000021', '0', '0.610000014', '0.370000005', '3.549999952', '0', '9', '9', '251', '1171', '1969']
['1844505072', '2016-04-02', '5367', '3.549999952', '3.549999952', '0', '0', '0', '3.549999952', '0', '0', '0', '263', '1177', '1889']
['1844505072', '2016-04-03', '2841', '1.879999995', '1.879999995', '0', '0', '0', '1.879999995', '0', '0', '0', '136', '1114', '1636']
['1844505072', '2016-04-04', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '669', '1347']
['1844505072', '2016-04-05', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1347']
['1844505072', '2016-04-06', '7', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1439', '1349']
['1844505072', '2016-04-07', '6344', '4.190000057', '4.190000057', '0', '0', '0', '4.190000057', '0', '0', '0', '290', '1150', '1965']
['1844505072', '2016-04-08', '5316', '3.50999999', '3.50999999', '0', '0', '0', '3.50999999', '0', '0', '0', '221', '1219', '1824']
['1844505072', '2016-04-09', '4979', '3.289999962', '3.289999962', '0', '0', '0', '3.289999962', '0', '0', '0', '184', '620', '1807']
['1844505072', '2016-04-10', '6556', '4.340000153', '4.340000153', '0', '0', '0', '4.329999924', '0', '0', '0', '305', '810', '1971']
['1844505072', '2016-04-11', '5430', '3.589999914', '3.589999914', '0', '0', '0', '3.589999914', '0', '0', '0', '251', '1189', '1888']
['1844505072', '2016-04-12', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '426', '399']
['1927972279', '2016-04-01', '4317', '2.99000001', '2.99000001', '0', '0', '0.370000005', '2.619999886', '0', '0', '11', '192', '854', '2590']
['1927972279', '2016-04-02', '5662', '3.920000076', '3.920000076', '0', '0', '0', '3.920000076', '0', '0', '0', '267', '858', '2783']
['1927972279', '2016-04-03', '3198', '2.210000038', '2.210000038', '0', '0', '0', '2.210000038', '0', '0', '0', '146', '1183', '2449']
['1927972279', '2016-04-04', '2352', '1.629999995', '1.629999995', '0', '0', '0', '1.629999995', '0', '0', '0', '128', '829', '2380']
['1927972279', '2016-04-05', '2234', '1.549999952', '1.549999952', '0', '0', '0', '1.549999952', '0', '0', '0', '108', '912', '2344']
['1927972279', '2016-04-06', '1259', '0.870000005', '0.870000005', '0', '0', '0', '0.870000005', '0', '0', '0', '73', '938', '2202']
['1927972279', '2016-04-07', '768', '0.529999971', '0.529999971', '0', '0', '0', '0.529999971', '0', '0', '0', '43', '1397', '2130']
['1927972279', '2016-04-08', '519', '0.360000014', '0.360000014', '0', '0', '0', '0.360000014', '0', '0', '0', '34', '1406', '2088']
['1927972279', '2016-04-09', '2523', '1.75', '1.75', '0', '0', '0.370000005', '1.379999995', '0', '0', '9', '134', '1250', '2443']
['1927972279', '2016-04-10', '2105', '1.460000038', '1.460000038', '0', '0', '0', '1.460000038', '0', '0', '0', '139', '805', '2442']
['1927972279', '2016-04-11', '1209', '0.839999974', '0.839999974', '0', '0', '0', '0.839999974', '0', '0', '0', '73', '842', '2255']
['1927972279', '2016-04-12', '24', '0.02', '0.02', '0', '0', '0', '0.02', '0', '0', '0', '3', '161', '942']
['2022484408', '2016-04-01', '13603', '9.600000381', '9.600000381', '0', '5.460000038', '0.629999995', '3.50999999', '0', '72', '16', '213', '1139', '2645']
['2022484408', '2016-04-02', '5477', '3.839999914', '3.839999914', '0', '0', '0', '3.839999914', '0', '0', '0', '237', '1203', '2040']
['2022484408', '2016-04-03', '11144', '7.820000172', '7.820000172', '0', '1.789999962', '0.889999986', '5.139999866', '0', '25', '22', '279', '1114', '2395']
['2022484408', '2016-04-04', '15313', '11', '11', '0', '5.019999981', '1.289999962', '4.690000057', '0', '62', '19', '233', '1126', '2581']
['2022484408', '2016-04-05', '10805', '7.590000153', '7.590000153', '0', '0.720000029', '0.980000019', '5.889999866', '0', '36', '37', '298', '1069', '2735']
['2022484408', '2016-04-06', '15392', '10.93000031', '10.93000031', '0', '3.430000067', '1.75', '5.75', '0', '47', '42', '258', '1093', '2733']
['2022484408', '2016-04-07', '18247', '13.82999992', '13.82999992', '0', '7.110000134', '2.210000038', '4.510000229', '0', '72', '62', '252', '1054', '3021']
['2022484408', '2016-04-08', '13023', '9.260000229', '9.260000229', '0', '3.230000019', '0.560000002', '5.46999979', '0', '40', '12', '296', '1092', '2577']
['2022484408', '2016-04-09', '16267', '12.59000015', '12.59000015', '0', '5.75', '0.469999999', '6.369999886', '0', '44', '16', '302', '1078', '2811']
['2022484408', '2016-04-10', '10005', '7.019999981', '7.019999981', '0', '0.079999998', '1.049999952', '5.900000095', '0', '1', '23', '339', '1077', '2458']
['2022484408', '2016-04-11', '10106', '7.090000153', '7.090000153', '0', '1.210000038', '0.560000002', '5.329999924', '0', '41', '16', '272', '1111', '2568']
['2022484408', '2016-04-12', '6717', '4.71999979', '4.71999979', '0', '3.230000019', '0.219999999', '1.269999981', '0', '41', '5', '67', '551', '1140']
['2026352035', '2016-04-01', '2605', '1.620000005', '1.620000005', '0', '0', '0', '1.620000005', '0', '0', '0', '166', '729', '1407']
['2026352035', '2016-04-02', '1229', '0.75999999', '0.75999999', '0', '0', '0', '0.75999999', '0', '0', '0', '69', '795', '1237']
['2026352035', '2016-04-03', '2308', '1.429999948', '1.429999948', '0', '0', '0', '1.429999948', '0', '0', '0', '115', '720', '1330']
['2026352035', '2016-04-04', '6679', '4.139999866', '4.139999866', '0', '0', '0', '4.139999866', '0', '0', '0', '263', '644', '1583']
['2026352035', '2016-04-05', '5645', '3.5', '3.5', '0', '0', '0', '3.5', '0', '0', '0', '248', '621', '1538']
['2026352035', '2016-04-06', '3180', '1.970000029', '1.970000029', '0', '0', '0', '1.970000029', '0', '0', '0', '185', '738', '1421']
['2026352035', '2016-04-07', '2767', '1.720000029', '1.720000029', '0', '0', '0', '1.720000029', '0', '0', '0', '170', '673', '1392']
['2026352035', '2016-04-08', '3762', '2.329999924', '2.329999924', '0', '0', '0', '2.329999924', '0', '0', '0', '173', '719', '1425']
['2026352035', '2016-04-09', '3098', '1.919999957', '1.919999957', '0', '0', '0', '1.919999957', '0', '0', '0', '185', '700', '1413']
['2026352035', '2016-04-10', '5142', '3.190000057', '3.190000057', '0', '0', '0', '3.190000057', '0', '0', '0', '230', '654', '1515']
['2026352035', '2016-04-11', '3279', '2.029999971', '2.029999971', '0', '0', '0', '2.029999971', '0', '0', '0', '164', '694', '1405']
['2026352035', '2016-04-12', '1019', '0.629999995', '0.629999995', '0', '0', '0', '0.629999995', '0', '0', '0', '64', '223', '600']
['2320127002', '2016-04-01', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1324']
['2320127002', '2016-04-02', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1324']
['2320127002', '2016-04-03', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1324']
['2320127002', '2016-04-04', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1324']
['2320127002', '2016-04-05', '4931', '3.319999933', '3.319999933', '0', '0', '0', '3.319999933', '0', '0', '0', '175', '1265', '1708']
['2320127002', '2016-04-06', '6999', '4.71999979', '4.71999979', '0', '0', '0', '4.71999979', '0', '0', '0', '320', '1120', '1950']
['2320127002', '2016-04-07', '1846', '1.24000001', '1.24000001', '0', '0', '0', '1.24000001', '0', '0', '0', '93', '1347', '1508']
['2320127002', '2016-04-08', '3417', '2.299999952', '2.299999952', '0', '0', '0', '2.299999952', '0', '0', '0', '153', '1287', '1625']
['2320127002', '2016-04-09', '4863', '3.279999971', '3.279999971', '0', '0.059999999', '0.419999987', '2.799999952', '0', '1', '11', '208', '1220', '1772']
['2320127002', '2016-04-10', '2277', '1.529999971', '1.529999971', '0', '0', '0', '1.529999971', '0', '0', '0', '103', '1337', '1530']
['2320127002', '2016-04-11', '11230', '7.670000076', '7.670000076', '0', '0.889999986', '0.119999997', '6.659999847', '0', '10', '2', '390', '1038', '2206']
['2320127002', '2016-04-12', '2098', '1.409999967', '1.409999967', '0', '0', '0', '1.409999967', '0', '0', '0', '69', '617', '790']
['2347167796', '2016-03-29', '10272', '6.789999962', '6.789999962', '0', '0.159999996', '3.119999886', '3.5', '0', '2', '58', '208', '700', '2041']
['2347167796', '2016-03-30', '10533', '7.099999905', '7.099999905', '0', '1.769999981', '2.059999943', '3.269999981', '0', '21', '35', '255', '615', '2187']
['2347167796', '2016-03-31', '6760', '4.46999979', '4.46999979', '0', '0', '0', '4.46999979', '0', '0', '0', '250', '613', '1929']
['2347167796', '2016-04-01', '8328', '5.510000229', '5.510000229', '0', '0', '2', '3.5', '0', '0', '33', '212', '804', '1935']
['2347167796', '2016-04-02', '15459', '10.22000027', '10.22000027', '0', '3.589999914', '0.810000002', '5.820000172', '0', '51', '16', '327', '583', '2438']
['2347167796', '2016-04-03', '7485', '4.949999809', '4.949999809', '0', '0', '0', '4.949999809', '0', '0', '0', '324', '491', '2035']
['2347167796', '2016-04-04', '10254', '6.800000191', '6.800000191', '0', '1.419999957', '1.230000019', '4.159999847', '0', '21', '25', '231', '638', '2099']
['2347167796', '2016-04-05', '10114', '6.820000172', '6.820000172', '0', '1.639999986', '0.479999989', '4.679999828', '0', '18', '9', '269', '696', '2096']
['2347167796', '2016-04-06', '11107', '7.340000153', '7.340000153', '0', '0.899999976', '2.75999999', '3.680000067', '0', '14', '46', '196', '759', '2058']
['2347167796', '2016-04-07', '10320', '6.849999905', '6.849999905', '0', '0.680000007', '1.230000019', '4.940000057', '0', '15', '32', '315', '1002', '2338']
['2347167796', '2016-04-08', '10209', '6.75', '6.75', '0', '0.159999996', '0.349999994', '6.230000019', '0', '2', '6', '316', '711', '2104']
['2347167796', '2016-04-09', '16081', '10.63000011', '10.63000011', '0', '1.25', '1.820000052', '7.559999943', '0', '16', '32', '401', '970', '2488']
['2347167796', '2016-04-10', '10078', '6.829999924', '6.829999924', '0', '1.019999981', '0.119999997', '5.690000057', '0', '12', '3', '303', '463', '2164']
['2347167796', '2016-04-11', '10001', '6.610000134', '6.610000134', '0', '0.330000013', '2.930000067', '3.359999895', '0', '5', '52', '196', '788', '2009']
['2347167796', '2016-04-12', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '425', '399']

['2873212765', '2016-04-01', '890', '0.600000024', '0.600000024', '0', '0', '0', '0.600000024', '0', '0', '0', '41', '1399', '1335']
['2873212765', '2016-04-02', '2214', '1.49000001', '1.49000001', '0', '0', '0', '1.49000001', '0', '0', '0', '197', '1243', '1559']
['2873212765', '2016-04-03', '7640', '5.130000114', '5.130000114', '0', '0.189999998', '0.800000012', '4.150000095', '0', '3', '15', '315', '1107', '1845']
['2873212765', '2016-04-04', '9713', '6.53000021', '6.53000021', '0', '0.340000004', '0.889999986', '5.289999962', '0', '6', '24', '355', '1055', '2046']
['2873212765', '2016-04-05', '8432', '5.670000076', '5.670000076', '0', '0', '0', '5.650000095', '0.01', '0', '0', '374', '1066', '1953']
['2873212765', '2016-04-06', '7350', '4.940000057', '4.940000057', '0', '0', '0', '4.940000057', '0', '0', '0', '382', '1058', '1910']
['2873212765', '2016-04-07', '9353', '6.309999943', '6.309999943', '0', '0.370000005', '0.689999998', '5.239999771', '0', '5', '17', '363', '1055', '2035']
['2873212765', '2016-04-08', '7157', '4.809999943', '4.809999943', '0', '0', '0', '4.809999943', '0', '0', '0', '380', '1060', '1944']
['2873212765', '2016-04-09', '14103', '9.56000042', '9.56000042', '0', '3.019999981', '0.409999996', '6.139999866', '0.01', '46', '8', '288', '1098', '2257']
['2873212765', '2016-04-10', '5290', '3.549999952', '3.549999952', '0', '0.039999999', '0.340000004', '3.170000076', '0', '1', '8', '251', '1180', '1724']
['2873212765', '2016-04-11', '7497', '5.039999962', '5.039999962', '0', '0', '0', '5.039999962', '0', '0', '0', '357', '882', '1741']
['2873212765', '2016-04-12', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '0']
['2891001357', '2016-03-29', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1920']
['2891001357', '2016-03-30', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1920']
['2891001357', '2016-03-31', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1920']
['2891001357', '2016-04-01', '0', '0', '0', '4.828032017', '0', '0', '0', '0', '0', '660', '0', '780', '4562']
['2891001357', '2016-04-02', '4126', '3.220000029', '0', '3.218688011', '0', '0', '3.220000029', '0', '0', '0', '720', '720', '2881']
['2891001357', '2016-04-03', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1920']
['2891001357', '2016-04-04', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1920']
['2891001357', '2016-04-05', '2063', '1.610000014', '0', '1.609344006', '0', '0', '1.610000014', '0', '0', '0', '630', '99', '1144']
['3372868164', '2016-04-01', '5785', '3.950000048', '3.950000048', '0', '0', '0', '3.910000086', '0.039999999', '0', '0', '311', '1129', '1852']
['3372868164', '2016-04-02', '7625', '5.230000019', '5.230000019', '0', '1.679999948', '0.039999999', '3.5', '0.01', '24', '1', '341', '1074', '2069']
['3372868164', '2016-04-03', '4706', '3.210000038', '3.210000038', '0', '0', '0', '3.210000038', '0', '0', '0', '299', '1141', '1816']
['3372868164', '2016-04-04', '5861', '4.019999981', '4.019999981', '0', '1.299999952', '0.219999999', '2.49000001', '0.01', '20', '7', '233', '1180', '1878']
['3372868164', '2016-04-05', '4460', '3.039999962', '3.039999962', '0', '0', '0', '3.019999981', '0.029999999', '0', '0', '248', '1192', '1787']
['3372868164', '2016-04-06', '6406', '4.389999866', '4.389999866', '0', '0.779999971', '0.090000004', '3.519999981', '0.01', '17', '4', '325', '1094', '2010']
['3372868164', '2016-04-07', '7392', '5.099999905', '5.099999905', '0', '0.870000005', '0.159999996', '4.050000191', '0.02', '14', '9', '332', '1085', '2038']
['3372868164', '2016-04-08', '5551', '3.789999962', '3.789999962', '0', '0', '0', '3.769999981', '0.01', '0', '0', '282', '1158', '1815']
['3372868164', '2016-04-09', '8827', '6.25', '6.25', '0', '1.769999981', '0.479999989', '4', '0.01', '21', '10', '346', '1063', '2062']
['3372868164', '2016-04-10', '4662', '3.180000067', '3.180000067', '0', '1.039999962', '0.150000006', '1.99000001', '0', '22', '4', '152', '735', '1276']
['3977333714', '2016-04-01', '4499', '3.00999999', '3.00999999', '0', '0', '0', '3.00999999', '0', '0', '0', '168', '842', '1288']
['3977333714', '2016-04-02', '7618', '5.099999905', '5.099999905', '0', '0', '0.180000007', '4.909999847', '0', '0', '6', '302', '842', '1490']
['3977333714', '2016-04-03', '11508', '7.699999809', '7.699999809', '0', '2.170000076', '0.839999974', '4.690000057', '0', '29', '22', '282', '748', '1630']
['3977333714', '2016-04-04', '11943', '7.989999771', '7.989999771', '0', '1.029999971', '2.00999999', '4.949999809', '0', '16', '43', '297', '710', '1648']
['3977333714', '2016-04-05', '12303', '8.229999542', '8.229999542', '0', '1.710000038', '1.350000024', '5.170000076', '0', '26', '32', '291', '605', '1649']
['3977333714', '2016-04-06', '15425', '10.31999969', '10.31999969', '0', '1.620000005', '1.820000052', '6.869999886', '0', '24', '45', '331', '614', '1783']
['3977333714', '2016-04-07', '8422', '5.630000114', '5.630000114', '0', '0', '3.599999905', '2.039999962', '0', '0', '81', '139', '815', '1431']
['3977333714', '2016-04-08', '10226', '6.840000153', '6.840000153', '0', '0', '4.440000057', '2.400000095', '0', '0', '101', '174', '685', '1524']
['3977333714', '2016-04-09', '14583', '9.760000229', '9.760000229', '0', '2.480000019', '1.74000001', '5.53000021', '0', '35', '36', '254', '697', '1697']
['3977333714', '2016-04-10', '3573', '2.390000105', '2.390000105', '0', '0.939999998', '0.409999996', '0.970000029', '0', '15', '8', '99', '866', '1232']
['3977333714', '2016-04-11', '3108', '2.140000105', '2.140000105', '0', '0.07', '0.039999999', '1.960000038', '0', '1', '1', '129', '894', '1223']
['3977333714', '2016-04-12', '759', '0.569999993', '0.569999993', '0', '0', '0', '0.569999993', '0', '0', '0', '17', '187', '182']
['4020332650', '2016-03-12', '5543', '3.970000029', '3.970000029', '0', '0', '0', '3.960000038', '0.01', '0', '0', '254', '757', '2990']
['4020332650', '2016-03-13', '3226', '2.309999943', '2.309999943', '0', '0', '0', '2.279999971', '0', '0', '0', '136', '771', '2480']
['4020332650', '2016-03-14', '3023', '2.170000076', '2.170000076', '0', '0', '0', '2.140000105', '0', '0', '0', '145', '1005', '2570']
['4020332650', '2016-03-15', '5906', '4.230000019', '4.230000019', '0', '0', '0.159999996', '4.039999962', '0', '0', '10', '215', '874', '3016']
['4020332650', '2016-03-16', '12483', '8.989999771', '8.989999771', '0', '1.450000048', '0.569999993', '6.900000095', '0', '25', '14', '309', '599', '3830']
['4020332650', '2016-03-17', '8940', '6.409999847', '6.409999847', '0', '0', '0', '0.610000014', '0.039999999', '0', '0', '47', '986', '3706']
['4020332650', '2016-03-18', '368', '0.25999999', '0.25999999', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '2024']
['4020332650', '2016-03-19', '5702', '4.090000153', '4.090000153', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '2980']
['4020332650', '2016-03-20', '10330', '7.409999847', '7.409999847', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '3728']
['4020332650', '2016-03-21', '8778', '6.289999962', '6.289999962', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '3348']
['4020332650', '2016-03-22', '6662', '4.78000021', '4.78000021', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '3162']
['4020332650', '2016-03-23', '6309', '4.519999981', '4.519999981', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '3140']
['4020332650', '2016-03-24', '1951', '1.409999967', '1.409999967', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1980']
['4020332650', '2016-03-25', '5563', '3.99000001', '3.99000001', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '3681']
['4020332650', '2016-03-26', '4370', '3.130000114', '3.130000114', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '3444']
['4020332650', '2016-03-27', '7144', '5.119999886', '5.119999886', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '3510']
['4020332650', '2016-03-28', '2106', '1.50999999', '1.50999999', '0', '0.02', '0.050000001', '0.209999993', '0', '31', '45', '75', '1289', '4010']
['4020332650', '2016-03-29', '4152', '2.980000019', '2.980000019', '0', '0', '0', '2.960000038', '0', '0', '0', '187', '1253', '2976']
['4020332650', '2016-03-30', '5400', '3.869999886', '3.869999886', '0', '0', '0', '3.849999905', '0', '0', '0', '258', '795', '3418']
['4020332650', '2016-03-31', '7428', '5.329999924', '5.329999924', '0', '0.870000005', '0.920000017', '3.50999999', '0', '18', '33', '261', '860', '3439']
['4020332650', '2016-04-01', '5351', '3.839999914', '3.839999914', '0', '0.620000005', '0.180000007', '3.00999999', '0', '15', '17', '210', '748', '3338']
['4020332650', '2016-04-02', '4299', '3.099999905', '3.099999905', '0', '0.090000004', '0.209999993', '2.74000001', '0.039999999', '3', '15', '162', '752', '2892']
['4020332650', '2016-04-03', '6107', '4.380000114', '4.380000114', '0', '0', '0', '4.360000134', '0', '0', '0', '265', '776', '3313']
['4020332650', '2016-04-04', '6429', '4.599999905', '4.599999905', '0', '0', '0.949999988', '3.650000095', '0', '0', '28', '193', '741', '3118']
['4020332650', '2016-04-05', '6880', '4.929999828', '4.929999828', '0', '0.5', '0.75999999', '3.650000095', '0', '7', '19', '165', '1249', '2966']
['4020332650', '2016-04-06', '7476', '5.360000134', '5.360000134', '0', '0', '0', '5.309999943', '0', '0', '0', '263', '920', '3253']
['4020332650', '2016-04-07', '6581', '4.71999979', '4.71999979', '0', '0', '0.289999992', '4.389999866', '0', '0', '8', '241', '1191', '3032']
['4020332650', '2016-04-08', '10480', '7.510000229', '7.510000229', '0', '0.409999996', '1.470000029', '5.010000229', '0.039999999', '6', '37', '272', '1125', '4034']
['4020332650', '2016-04-09', '7734', '5.550000191', '5.550000191', '0', '1.159999967', '0.49000001', '3.819999933', '0.059999999', '20', '12', '223', '1185', '3264']
['4020332650', '2016-04-10', '5129', '3.680000067', '3.680000067', '0', '0.180000007', '0.239999995', '3.210000038', '0.01', '5', '7', '176', '1178', '2817']
['4020332650', '2016-04-11', '2993', '2.150000095', '2.150000095', '0', '0', '0', '2.089999914', '0', '0', '0', '114', '888', '2507']
['4020332650', '2016-04-12', '8', '0.01', '0.01', '0', '0', '0', '0.01', '0', '0', '0', '1', '321', '446']
['4057192912', '2016-03-12', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1777']
['4057192912', '2016-03-13', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1777']
['4057192912', '2016-03-14', '8433', '6.230000019', '6.230000019', '0', '2.450000048', '0.330000013', '3.440000057', '0', '30', '7', '135', '1268', '2453']
['4057192912', '2016-03-15', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1776']
['4057192912', '2016-03-16', '2139', '1.559999943', '1.559999943', '0', '0', '1.299999952', '0.25999999', '0', '0', '28', '15', '1397', '1935']
['4057192912', '2016-03-17', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1776']
['4057192912', '2016-03-18', '949', '0.689999998', '0.689999998', '0', '0', '0', '0.689999998', '0', '0', '0', '34', '1406', '1870']
['4057192912', '2016-03-19', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1777']
['4057192912', '2016-03-20', '44', '0.029999999', '0.029999999', '0', '0', '0', '0.029999999', '0', '0', '0', '2', '1438', '1782']
['4057192912', '2016-03-21', '2660', '1.940000057', '1.940000057', '0', '0', '0', '1.940000057', '0', '0', '0', '46', '1394', '1978']
['4057192912', '2016-03-22', '5561', '4.190000057', '4.190000057', '0', '0', '0', '4.070000172', '0', '0', '0', '169', '1271', '2296']
['4057192912', '2016-03-23', '7239', '5.340000153', '5.340000153', '0', '0.550000012', '0.360000014', '4.380000114', '0', '7', '7', '190', '1236', '2484']
['4057192912', '2016-03-24', '7', '0.01', '0.01', '0', '0', '0', '0.01', '0', '0', '0', '1', '1439', '1787']
['4057192912', '2016-03-25', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1776']
['4057192912', '2016-03-26', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1776']

['4057192912', '2016-03-27', '2275', '1.679999948', '1.679999948', '0', '0', '0', '1.659999967', '0', '0', '0', '86', '1354', '2005']
['4057192912', '2016-03-28', '8', '0.01', '0.01', '0', '0', '0', '0.01', '0', '0', '0', '1', '1439', '1778']
['4057192912', '2016-03-29', '5137', '3.75999999', '3.75999999', '0', '0', '0', '3.75999999', '0', '0', '0', '160', '1280', '2293']
['4057192912', '2016-03-30', '5419', '4', '4.570000172', '0.055842999', '0', '0', '3.910000086', '0.059999999', '0', '0', '145', '1295', '2259']
['4057192912', '2016-03-31', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1776']
['4057192912', '2016-04-01', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1776']
['4057192912', '2016-04-02', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1776']
['4057192912', '2016-04-03', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1776']
['4057192912', '2016-04-04', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1776']
['4057192912', '2016-04-05', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1776']
['4057192912', '2016-04-06', '18', '0.01', '0.01', '0', '0', '0', '0.01', '0', '0', '0', '2', '1438', '1780']
['4057192912', '2016-04-07', '4', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1439', '1778']
['4057192912', '2016-04-08', '8426', '6.159999847', '6.159999847', '0', '0.129999995', '5.489999771', '0.540000021', '0', '2', '120', '25', '1293', '2360']
['4057192912', '2016-04-09', '1650', '1.210000038', '1.210000038', '0', '0', '0', '1.210000038', '0', '0', '0', '60', '1380', '1952']
['4057192912', '2016-04-10', '3434', '2.50999999', '2.50999999', '0', '0.07', '0.300000012', '2.140000105', '0', '1', '7', '108', '1324', '2101']
['4057192912', '2016-04-11', '6801', '4.980000019', '4.980000019', '0', '0', '0', '4.96999979', '0', '0', '0', '193', '1247', '2393']
['4057192912', '2016-04-12', '187', '0.140000001', '0.140000001', '0', '0', '0', '0.140000001', '0', '0', '0', '11', '400', '538']
['4319703577', '2016-03-29', '5643', '3.789999962', '3.789999962', '0', '0.230000004', '0.330000013', '3.230000019', '0', '3', '8', '199', '683', '1958']
['4319703577', '2016-03-30', '9043', '6.070000172', '6.070000172', '0', '0.25', '0.430000007', '5.369999886', '0', '4', '12', '244', '702', '2141']
['4319703577', '2016-03-31', '8144', '5.460000038', '5.460000038', '0', '0.25', '0.610000014', '4.610000134', '0', '4', '17', '247', '1125', '2129']
['4319703577', '2016-04-01', '9343', '6.269999981', '6.269999981', '0', '0.959999979', '0.850000024', '4.460000038', '0', '14', '20', '268', '654', '2216']
['4319703577', '2016-04-02', '8405', '5.659999847', '5.659999847', '0', '1.129999995', '0.189999998', '4.340000153', '0', '15', '4', '257', '621', '2154']
['4319703577', '2016-04-03', '8223', '5.519999981', '5.519999981', '0', '0.800000012', '1.50999999', '3.210000038', '0', '12', '37', '257', '551', '2178']
['4319703577', '2016-04-04', '10067', '6.760000229', '6.760000229', '0', '0.360000014', '1.419999957', '4.96999979', '0', '5', '39', '313', '578', '2308']
['4319703577', '2016-04-05', '8359', '5.630000114', '5.630000114', '0', '0.230000004', '0.529999971', '4.869999886', '0', '3', '14', '311', '638', '2201']
['4319703577', '2016-04-06', '10946', '7.349999905', '7.349999905', '0', '0.540000021', '2.089999914', '4.71999979', '0', '8', '51', '308', '569', '2341']
['4319703577', '2016-04-07', '9130', '6.150000095', '6.150000095', '0', '0.5', '0.379999995', '5.269999981', '0', '7', '11', '304', '668', '2236']
['4319703577', '2016-04-08', '6544', '4.409999847', '4.409999847', '0', '0.289999992', '0.25999999', '3.859999895', '0', '4', '6', '276', '1132', '2069']
['4319703577', '2016-04-09', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '0']
['4388161847', '2016-03-29', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1878']
['4388161847', '2016-03-30', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1878']
['4388161847', '2016-03-31', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1878']
['4388161847', '2016-04-01', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1878']
['4388161847', '2016-04-02', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1878']
['4388161847', '2016-04-03', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1878']
['4388161847', '2016-04-04', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1878']
['4388161847', '2016-04-05', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '994', '1296']
['4445114986', '2016-03-29', '2303', '1.549999952', '1.549999952', '0', '0', '0', '1.549999952', '0', '0', '0', '155', '807', '2010']
['4445114986', '2016-03-30', '2600', '1.74000001', '1.74000001', '0', '0', '0', '1.74000001', '0', '0', '0', '163', '1277', '2032']
['4445114986', '2016-03-31', '4804', '3.220000029', '3.220000029', '0', '0', '0', '3.220000029', '0', '0', '0', '238', '786', '2227']
['4445114986', '2016-04-01', '3271', '2.190000057', '2.190000057', '0', '0', '0', '2.190000057', '0', '0', '0', '205', '898', '2133']
['4445114986', '2016-04-02', '5406', '3.630000114', '3.630000114', '0', '0', '0', '3.609999895', '0', '0', '0', '273', '672', '2317']
['4445114986', '2016-04-03', '3146', '2.109999895', '2.109999895', '0', '0', '0', '2.109999895', '0', '0', '0', '171', '1269', '2058']
['4445114986', '2016-04-04', '2422', '1.629999995', '1.629999995', '0', '0', '0', '1.629999995', '0', '0', '0', '110', '1330', '1935']
['4445114986', '2016-04-05', '4239', '2.839999914', '2.839999914', '0', '0.059999999', '0.239999995', '2.529999971', '0', '1', '6', '235', '702', '2217']
['4445114986', '2016-04-06', '6911', '4.78000021', '4.78000021', '0', '2.319999933', '0.100000001', '2.359999895', '0', '28', '2', '215', '745', '2374']
['4445114986', '2016-04-07', '6667', '4.610000134', '4.610000134', '0', '2.019999981', '0.050000001', '2.549999952', '0', '24', '1', '208', '939', '2335']
['4445114986', '2016-04-08', '5543', '3.720000029', '3.720000029', '0', '0', '0', '3.720000029', '0', '0', '0', '266', '941', '2303']
['4445114986', '2016-04-09', '4195', '2.809999943', '2.809999943', '0', '0', '0', '2.809999943', '0', '0', '0', '239', '758', '2210']
['4445114986', '2016-04-10', '6625', '4.449999809', '4.449999809', '0', '0', '0', '4.449999809', '0', '0', '0', '316', '755', '2424']
['4445114986', '2016-04-11', '5986', '4.130000114', '4.130000114', '0', '1.950000048', '0.230000004', '1.950000048', '0', '23', '5', '195', '789', '2297']
['4445114986', '2016-04-12', '278', '0.189999998', '0.189999998', '0', '0', '0', '0.189999998', '0', '0', '0', '20', '253', '745']
['4558609924', '2016-04-01', '5336', '3.529999971', '3.529999971', '0', '0', '0', '3.529999971', '0', '0', '0', '258', '1182', '1902']
['4558609924', '2016-04-02', '3183', '2.099999905', '2.099999905', '0', '0', '0', '2.099999905', '0', '0', '0', '173', '1180', '1680']
['4558609924', '2016-04-03', '6176', '4.079999924', '4.079999924', '0', '0.07', '0.25999999', '3.75', '0', '1', '7', '269', '886', '1901']
['4558609924', '2016-04-04', '8205', '5.420000076', '5.420000076', '0', '0', '0', '5.420000076', '0', '0', '0', '367', '1073', '2078']
['4558609924', '2016-04-05', '6799', '4.489999771', '4.489999771', '0', '1.590000033', '0.860000014', '2.039999962', '0', '24', '14', '185', '1217', '1876']
['4558609924', '2016-04-06', '5668', '3.75', '3.75', '0', '0', '0', '3.75', '0', '0', '0', '259', '1181', '1853']
['4558609924', '2016-04-07', '7998', '5.289999962', '5.289999962', '0', '0.50999999', '0.25', '4.53000021', '0', '27', '12', '296', '1105', '2235']
['4558609924', '2016-04-08', '4195', '2.769999981', '2.769999981', '0', '0', '0', '2.769999981', '0', '0', '0', '241', '1199', '1778']
['4558609924', '2016-04-09', '5512', '3.640000105', '3.640000105', '0', '0', '0', '3.640000105', '0', '0', '0', '276', '1164', '1882']
['4558609924', '2016-04-10', '6263', '4.139999866', '4.139999866', '0', '0', '0', '4.130000114', '0', '0', '0', '290', '1150', '1906']
['4558609924', '2016-04-11', '8828', '5.840000153', '5.840000153', '0', '0', '0', '5.840000153', '0', '0', '0', '308', '1132', '2149']
['4558609924', '2016-04-12', '1260', '0.829999983', '0.829999983', '0', '0', '0', '0.819999993', '0', '0', '0', '76', '555', '722']
['4702921684', '2016-03-29', '6506', '5.28000021', '5.28000021', '0', '0.330000013', '0.270000011', '4.670000076', '0', '4', '5', '241', '760', '2886']
['4702921684', '2016-03-30', '7583', '6.150000095', '6.150000095', '0', '0.25', '0.550000012', '5.349999905', '0', '3', '13', '227', '742', '2915']
['4702921684', '2016-03-31', '6963', '5.650000095', '5.650000095', '0', '0', '0', '5.650000095', '0', '0', '0', '256', '759', '2895']
['4702921684', '2016-04-01', '7165', '5.809999943', '5.809999943', '0', '0', '0.370000005', '5.440000057', '0', '0', '9', '248', '708', '2923']
['4702921684', '2016-04-02', '10328', '8.380000114', '8.380000114', '0', '0', '1.460000038', '6.920000076', '0', '0', '32', '367', '475', '3323']
['4702921684', '2016-04-03', '12116', '9.829999924', '9.829999924', '0', '0.25', '2.849999905', '6.71999979', '0', '3', '57', '323', '471', '3357']
['4702921684', '2016-04-04', '7810', '6.360000134', '6.360000134', '0', '0.479999989', '1.200000048', '4.679999828', '0', '6', '27', '216', '746', '2931']
['4702921684', '2016-04-05', '6670', '5.409999847', '5.409999847', '0', '1.24000001', '0.800000012', '3.369999886', '0', '15', '16', '199', '770', '2848']
['4702921684', '2016-04-06', '7605', '6.179999828', '6.179999828', '0', '0.330000013', '0.209999993', '5.630000114', '0', '4', '4', '248', '708', '2943']
['4702921684', '2016-04-07', '6585', '5.340000153', '5.340000153', '0', '0', '0', '5.340000153', '0', '0', '0', '210', '770', '2822']
['4702921684', '2016-04-08', '8184', '6.639999866', '6.639999866', '0', '0', '0.620000005', '5.949999809', '0', '0', '15', '247', '808', '2981']
['4702921684', '2016-04-09', '14002', '11.35999966', '11.35999966', '0', '0.610000014', '2.680000067', '8.06000042', '0', '8', '56', '381', '407', '3597']
['4702921684', '2016-04-10', '11135', '9.029999733', '9.029999733', '0', '0.079999998', '1.159999967', '7.789999962', '0', '1', '25', '331', '528', '3224']
['4702921684', '2016-04-11', '6499', '5.269999981', '5.269999981', '0', '0', '0', '5.269999981', '0', '0', '0', '207', '809', '2677']
['4702921684', '2016-04-12', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '0']
['5553957443', '2016-04-01', '12409', '8.100000381', '8.100000381', '0', '2.900000095', '0.629999995', '4.579999924', '0', '51', '12', '235', '782', '2142']
['5553957443', '2016-04-02', '2937', '1.919999957', '1.919999957', '0', '0', '0', '1.909999967', '0', '0', '0', '181', '356', '1615']
['5553957443', '2016-04-03', '1515', '0.99000001', '0.99000001', '0', '0', '0', '0.99000001', '0', '0', '0', '93', '507', '1481']
['5553957443', '2016-04-04', '8921', '5.880000114', '5.880000114', '0', '2.069999933', '0.439999998', '3.359999895', '0', '27', '8', '198', '754', '1892']
['5553957443', '2016-04-05', '11306', '7.380000114', '7.380000114', '0', '2.309999943', '0.980000019', '4.090000153', '0', '40', '26', '218', '772', '2086']
['5553957443', '2016-04-06', '12252', '8', '8', '0', '2.410000086', '1.700000048', '3.890000105', '0', '33', '28', '229', '745', '2044']
['5553957443', '2016-04-07', '15444', '10.07999992', '10.07999992', '0', '3.269999981', '1.730000019', '5.079999924', '0', '51', '39', '243', '731', '2249']
['5553957443', '2016-04-08', '9938', '6.489999771', '6.489999771', '0', '2.140000105', '1.279999971', '3.079999924', '0', '38', '24', '193', '767', '2019']
['5553957443', '2016-04-09', '4599', '3', '3', '0', '0', '0', '3', '0', '0', '0', '176', '578', '1692']
['5553957443', '2016-04-10', '5594', '3.650000095', '3.650000095', '0', '0.280000001', '1.480000019', '1.889999986', '0', '4', '25', '150', '552', '1712']
['5553957443', '2016-04-11', '11906', '7.769999981', '7.769999981', '0', '2.25999999', '1.519999981', '3.99000001', '0', '32', '27', '234', '688', '2065']
['5553957443', '2016-04-12', '3436', '2.24000001', '2.24000001', '0', '0.5', '0.670000017', '1.049999952', '0', '7', '11', '50', '61', '633']
['5577150313', '2016-04-01', '10461', '7.869999886', '7.869999886', '0', '4.760000229', '0.850000024', '2.25', '0', '99', '31', '142', '721', '3625']
['5577150313', '2016-04-02', '14873', '11.10999966', '11.10999966', '0', '8.18999958', '0.600000024', '2.309999943', '0', '202', '36', '153', '663', '4430']
['5577150313', '2016-04-03', '9917', '7.409999847', '7.409999847', '0', '1.99000001', '0.970000029', '4.440000057', '0', '58', '27', '240', '700', '3427']
['5577150313', '2016-04-04', '7401', '5.559999943', '5.559999943', '0', '2.319999933', '0.360000014', '2.880000114', '0', '70', '19', '204', '689', '3492']
['5577150313', '2016-04-05', '8964', '6.699999809', '6.699999809', '0', '3.970000029', '0.189999998', '2.529999971', '0', '107', '18', '145', '756', '3597']
['5577150313', '2016-04-06', '11080', '8.300000191', '8.300000191', '0', '3.130000114', '1.370000005', '3.809999943', '0', '83', '52', '190', '695', '3765']
['5577150313', '2016-04-07', '4499', '3.359999895', '3.359999895', '0', '0.889999986', '0.25999999', '2.210000038', '0', '31', '11', '146', '756', '2775']
['5577150313', '2016-04-08', '4363', '3.25999999', '3.25999999', '0', '0.129999995', '0.059999999', '3.079999924', '0', '8', '2', '156', '813', '2486']
['5577150313', '2016-04-09', '10494', '7.840000153', '7.840000153', '0', '4.909999847', '0.779999971', '2.150000095', '0', '123', '62', '138', '601', '3817']
['5577150313', '2016-04-10', '9776', '7.380000114', '7.380000114', '0', '2.930000067', '1.429999948', '3.019999981', '0', '80', '35', '162', '721', '3378']
['5577150313', '2016-04-11', '2862', '2.140000105', '2.140000105', '0', '1.039999962', '0.25', '0.839999974', '0', '39', '17', '54', '209', '1511']
['6117666160', '2016-04-01', '7444', '5.619999886', '5.619999886', '0', '0', '0', '5.619999886', '0', '0', '0', '286', '568', '2210']
['6117666160', '2016-04-02', '19658', '14.84000015', '14.84000015', '0', '0.239999995', '2.089999914', '12.51000023', '0', '3', '30', '475', '466', '2884']
['6117666160', '2016-04-03', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1496']
['6117666160', '2016-04-04', '8468', '6.389999866', '6.389999866', '0', '0.180000007', '0.639999986', '5.570000172', '0', '2', '11', '279', '1148', '2262']
['6117666160', '2016-04-05', '9910', '7.480000019', '7.480000019', '0', '0', '0', '7.480000019', '0', '0', '0', '384', '990', '2445']
['6117666160', '2016-04-06', '12409', '9.369999886', '9.369999886', '0', '0', '0', '9.369999886', '0', '0', '0', '491', '388', '2694']
['6117666160', '2016-04-07', '4853', '3.660000086', '3.660000086', '0', '0', '0', '3.660000086', '0', '0', '0', '156', '770', '1903']
['6117666160', '2016-04-08', '8955', '6.760000229', '6.760000229', '0', '0', '0', '6.730000019', '0', '0', '0', '422', '1018', '2482']
['6117666160', '2016-04-09', '10789', '8.149999619', '8.149999619', '0', '0', '0', '8.149999619', '0', '0', '0', '506', '413', '2617']
['6117666160', '2016-04-10', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '0']
['6290855005', '2016-04-01', '6633', '5.010000229', '5.010000229', '0', '0', '0', '5.010000229', '0', '0', '0', '280', '1160', '2778']
['6290855005', '2016-04-02', '9548', '7.21999979', '7.21999979', '0', '2.019999981', '3.680000067', '1.519999981', '0', '25', '107', '113', '1195', '3119']
['6290855005', '2016-04-03', '0', '0', '0', '0', '0', '0', '0', '0', '33', '0', '0', '1407', '2664']
['6290855005', '2016-04-04', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '2060']
['6290855005', '2016-04-05', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '2060']
['6290855005', '2016-04-06', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '2060']
['6290855005', '2016-04-07', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '2060']
['6290855005', '2016-04-08', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '2060']
['6290855005', '2016-04-09', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '2060']
['6290855005', '2016-04-10', '0', '0', '0', '0', '0', '0', '0', '0', '20', '0', '0', '494', '735']
['6391747486', '2016-04-01', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1820']
['6391747486', '2016-04-02', '2101', '2.029999971', '0', '2.027772903', '2.029999971', '0', '0', '0', '46', '0', '0', '1394', '2224']
['6391747486', '2016-04-03', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1820']
['6391747486', '2016-04-04', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1820']
['6391747486', '2016-04-05', '9766', '7.510000229', '0.779999971', '6.72705698', '0', '0.050000001', '7.460000038', '0', '0', '6', '301', '1133', '2442']
['6391747486', '2016-04-06', '165', '0.129999995', '0.129999995', '0', '0', '0', '0.129999995', '0', '0', '0', '8', '1432', '1849']
['6391747486', '2016-04-07', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1822']

['6391747486', '2016-04-08', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1820']
['6391747486', '2016-04-09', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '198', '251']
['6775888955', '2016-04-01', '7225', '5.179999828', '5.179999828', '0', '1.730000019', '1.269999981', '2.180000067', '0', '25', '50', '163', '1189', '3065']
['6775888955', '2016-04-02', '1988', '1.429999948', '1.429999948', '0', '0', '0', '1.429999948', '0', '0', '0', '79', '909', '2207']
['6775888955', '2016-04-03', '1577', '1.129999995', '1.129999995', '0', '0.07', '0.889999986', '0.170000002', '0', '1', '17', '8', '1414', '1977']
['6775888955', '2016-04-04', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1841']
['6775888955', '2016-04-05', '9348', '6.699999809', '6.699999809', '0', '1.129999995', '2.039999962', '3.140000105', '0', '56', '133', '240', '1011', '4286']
['6775888955', '2016-04-06', '11761', '8.430000305', '8.430000305', '0', '1.309999943', '2.440000057', '4.679999828', '0', '24', '99', '300', '550', '3920']
['6775888955', '2016-04-07', '13987', '10.02999973', '10.02999973', '0', '2.869999886', '3.339999914', '3.819999933', '0', '46', '114', '250', '739', '3856']
['6775888955', '2016-04-08', '4131', '2.960000038', '2.960000038', '0', '1.370000005', '0.610000014', '0.980000019', '0', '27', '30', '75', '1308', '2584']
['6775888955', '2016-04-09', '14', '0.01', '0.01', '0', '0', '0', '0.01', '0', '0', '0', '1', '601', '787']
['6962181067', '2016-03-30', '15491', '10.23999977', '10.23999977', '0', '1.289999962', '4.489999771', '4.460000038', '0', '18', '77', '272', '641', '2244']
['6962181067', '2016-03-31', '14097', '9.319999695', '9.319999695', '0', '3.5', '1.919999957', '3.900000095', '0', '50', '32', '234', '595', '2188']
['6962181067', '2016-04-01', '10467', '6.980000019', '6.980000019', '0', '0.699999988', '2.430000067', '3.849999905', '0', '9', '45', '252', '602', '2014']
['6962181067', '2016-04-02', '12437', '8.300000191', '8.300000191', '0', '3.75999999', '1.289999962', '3.24000001', '0', '50', '24', '219', '732', '2115']
['6962181067', '2016-04-03', '12307', '8.140000343', '8.140000343', '0', '1.00999999', '3.25999999', '3.869999886', '0', '14', '51', '218', '589', '2055']
['6962181067', '2016-04-04', '18952', '12.80000019', '12.80000019', '0', '5.909999847', '1.230000019', '5.659999847', '0', '73', '20', '327', '570', '2437']
['6962181067', '2016-04-05', '12010', '7.940000057', '7.940000057', '0', '2.380000114', '0.949999988', '4.610000134', '0', '38', '17', '287', '692', '2158']
['6962181067', '2016-04-06', '12480', '8.859999657', '8.25', '3.97279501', '4.179999828', '0.689999998', '4', '0', '55', '14', '276', '593', '2170']
['6962181067', '2016-04-07', '13417', '9.649999619', '8.869999886', '1.926301956', '3.390000105', '1.25', '4.909999847', '0.100000001', '45', '16', '284', '665', '2244']
['6962181067', '2016-04-08', '14400', '10.88000011', '9.520000458', '5.45686388', '2.470000029', '2.880000114', '5.53000021', '0', '27', '37', '276', '697', '2188']
['6962181067', '2016-04-09', '12495', '8.260000229', '8.260000229', '0', '2.210000038', '1.090000033', '4.960000038', '0', '33', '19', '324', '609', '2231']
['6962181067', '2016-04-10', '10148', '6.710000038', '6.710000038', '0', '1.360000014', '0.219999999', '5.130000114', '0', '19', '7', '306', '679', '2100']
['6962181067', '2016-04-11', '12362', '9.090000153', '8.170000076', '2.696455002', '1.090000033', '2.730000019', '5.269999981', '0', '21', '38', '297', '678', '2188']
['6962181067', '2016-04-12', '5893', '3.900000095', '3.900000095', '0', '2.880000114', '0.560000002', '0.460000008', '0', '43', '9', '48', '146', '917']
['7007744171', '2016-04-01', '11680', '9.06000042', '7.809999943', '4.901282787', '4.489999771', '0.330000013', '4.239999771', '0', '50', '7', '244', '1139', '2573']
['7007744171', '2016-04-02', '10976', '7.340000153', '7.340000153', '0', '0.550000012', '0.670000017', '6.130000114', '0', '9', '16', '271', '1075', '2575']
['7007744171', '2016-04-03', '16806', '11.23999977', '11.23999977', '0', '6.409999847', '1.370000005', '3.470000029', '0', '104', '31', '230', '1002', '3086']
['7007744171', '2016-04-04', '15266', '11.39999962', '10.21000004', '5.189849854', '5.800000191', '0.75999999', '4.789999962', '0.050000001', '70', '21', '292', '1057', '2886']
['7007744171', '2016-04-05', '12084', '9.140000343', '8.079999924', '4.836380005', '4.389999866', '0.460000008', '4.289999962', '0', '50', '6', '284', '1030', '2676']
['7007744171', '2016-04-06', '13513', '10.25', '9.069999695', '4.835720062', '5.349999905', '0.330000013', '4.559999943', '0', '64', '8', '270', '1098', '2811']
['7007744171', '2016-04-07', '14100', '10.57999992', '9.430000305', '4.875989914', '5.099999905', '1.190000057', '4.28000021', '0', '61', '33', '265', '1015', '2840']
['7007744171', '2016-04-08', '12627', '9.649999619', '8.449999809', '4.842319965', '4.699999809', '0.74000001', '4.210000038', '0', '54', '22', '301', '1063', '2871']
['7007744171', '2016-04-09', '10345', '6.920000076', '6.920000076', '0', '0.07', '0.270000011', '6.579999924', '0', '2', '6', '358', '1074', '2613']
['7007744171', '2016-04-10', '10146', '6.789999962', '6.789999962', '0', '0.07', '0.610000014', '6.110000134', '0', '1', '12', '397', '1030', '2700']
['7007744171', '2016-04-11', '12168', '8.140000343', '8.140000343', '0', '1.049999952', '0.790000021', '6.289999962', '0', '18', '27', '375', '1020', '2871']
['7007744171', '2016-04-12', '7413', '5.769999981', '4.960000038', '4.869782925', '4.5', '0.340000004', '0.939999998', '0', '53', '6', '43', '405', '1023']
['7086361926', '2016-04-01', '11463', '7.670000076', '7.670000076', '0', '2.829999924', '1.889999986', '2.930000067', '0', '38', '30', '154', '777', '2496']
['7086361926', '2016-04-02', '87', '0.02', '0.02', '0', '0', '0', '0.01', '0', '0', '0', '2', '872', '1641']
['7086361926', '2016-04-03', '1949', '1.309999943', '1.309999943', '0', '0.230000004', '0.349999994', '0.730000019', '0', '3', '6', '27', '1404', '1794']
['7086361926', '2016-04-04', '6101', '3.869999886', '3.869999886', '0', '0.529999971', '0.230000004', '3.099999905', '0', '31', '24', '138', '1247', '2421']
['7086361926', '2016-04-05', '7478', '4.989999771', '4.989999771', '0', '1.799999952', '0.529999971', '2.609999895', '0.029999999', '25', '33', '132', '1159', '2439']
['7086361926', '2016-04-06', '7352', '4.730000019', '4.730000019', '0', '1.409999967', '0.779999971', '2.529999971', '0', '19', '14', '124', '814', '2233']
['7086361926', '2016-04-07', '14604', '10.81999969', '10.81999969', '0', '7.230000019', '1.120000005', '2.430000067', '0.029999999', '76', '30', '127', '695', '2862']
['7086361926', '2016-04-08', '9634', '6.519999981', '6.519999981', '0', '2.5', '1.399999976', '2.589999914', '0', '50', '48', '140', '797', '2752']
['7086361926', '2016-04-09', '7338', '4.670000076', '4.670000076', '0', '1.080000043', '0.129999995', '3.460000038', '0', '27', '5', '204', '717', '2519']
['7086361926', '2016-04-10', '569', '0.349999994', '0.349999994', '0', '0', '0', '0.340000004', '0', '0', '0', '27', '1368', '1799']
['7086361926', '2016-04-11', '6242', '3.920000076', '3.920000076', '0', '0.74000001', '0.230000004', '2.930000067', '0', '46', '22', '126', '741', '2543']
['7086361926', '2016-04-12', '430', '0.25999999', '0.25999999', '0', '0', '0', '0.25999999', '0', '0', '0', '14', '75', '625']
['8053475328', '2016-04-02', '20188', '15.61999989', '15.61999989', '0', '12.06000042', '0.850000024', '2.710000038', '0', '124', '19', '172', '1125', '3377']
['8053475328', '2016-04-03', '25701', '20.13999939', '20.13999939', '0', '16.81999969', '1.629999995', '1.690000057', '0', '165', '36', '97', '1142', '3697']
['8053475328', '2016-04-04', '17395', '13.21000004', '13.21000004', '0', '9.670000076', '0.180000007', '3.349999905', '0', '100', '4', '213', '1123', '3209']
['8053475328', '2016-04-05', '17167', '13.40999985', '13.40999985', '0', '9.960000038', '0.310000002', '3.140000105', '0', '98', '8', '184', '1150', '3167']
['8053475328', '2016-04-06', '16435', '12.42000008', '12.42000008', '0', '8.960000038', '0.550000012', '2.910000086', '0', '100', '14', '191', '1135', '3122']
['8053475328', '2016-04-07', '17078', '13.19999981', '13.19999981', '0', '9.970000267', '0.239999995', '2.99000001', '0', '101', '6', '190', '1143', '3176']
['8053475328', '2016-04-08', '11693', '9.539999962', '9.539999962', '0', '6.769999981', '0.25999999', '2.5', '0', '60', '6', '153', '1221', '2790']
['8053475328', '2016-04-09', '11159', '9.140000343', '9.140000343', '0', '6.690000057', '0.25', '2.190000057', '0', '59', '6', '120', '1255', '2715']
['8053475328', '2016-04-10', '10118', '7.730000019', '7.730000019', '0', '3.049999952', '0.800000012', '3.880000114', '0', '30', '18', '207', '1185', '2684']
['8053475328', '2016-04-11', '16064', '12.72000027', '12.72000027', '0', '9.979999542', '0.360000014', '2.380000114', '0', '96', '8', '155', '1181', '3097']
['8053475328', '2016-04-12', '290', '0.209999993', '0.209999993', '0', '0', '0', '0.209999993', '0', '0', '0', '16', '599', '791']
['8253242879', '2016-04-01', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1429']
['8253242879', '2016-04-02', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1429']
['8253242879', '2016-04-03', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1429']
['8253242879', '2016-04-04', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1429']
['8253242879', '2016-04-05', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '1429']
['8253242879', '2016-04-06', '1931', '1.279999971', '1.279999971', '0', '0', '0', '1.279999971', '0', '0', '0', '94', '1346', '1607']
['8253242879', '2016-04-07', '5181', '3.420000076', '3.420000076', '0', '1', '0.910000026', '1.50999999', '0.01', '15', '15', '107', '1303', '1776']
['8253242879', '2016-04-08', '12026', '9.149999619', '9.149999619', '0', '5.699999809', '0.930000007', '2.50999999', '0', '47', '13', '150', '1230', '2162']
['8253242879', '2016-04-09', '5360', '3.539999962', '3.539999962', '0', '0.540000021', '1.549999952', '1.460000038', '0', '8', '28', '148', '1256', '1832']
['8253242879', '2016-04-10', '2545', '1.679999948', '1.679999948', '0', '0', '0', '1.669999957', '0.02', '0', '0', '126', '1314', '1657']
['8253242879', '2016-04-11', '1636', '1.080000043', '1.080000043', '0', '0', '0', '1.080000043', '0', '0', '0', '86', '1139', '1377']
['8253242879', '2016-04-12', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1440', '0']
['8378563200', '2016-04-01', '14179', '11.23999977', '11.23999977', '0', '6.230000019', '1.059999943', '3.960000038', '0', '73', '21', '195', '719', '3669']
['8378563200', '2016-04-02', '3358', '2.660000086', '2.660000086', '0', '0', '0', '2.660000086', '0', '0', '0', '144', '657', '2702']
['8378563200', '2016-04-03', '9152', '7.260000229', '7.260000229', '0', '1.99000001', '0.819999993', '4.449999809', '0', '25', '13', '243', '600', '3304']
['8378563200', '2016-04-04', '13935', '11.05000019', '11.05000019', '2.092147112', '4.090000153', '0.790000021', '6.170000076', '0', '105', '16', '220', '658', '4234']
['8378563200', '2016-04-05', '12846', '10.18999958', '10.18999958', '2.253081083', '5', '0.75', '4.440000057', '0', '113', '15', '189', '686', '4128']
['8378563200', '2016-04-06', '9124', '7.239999771', '7.239999771', '2.092147112', '0', '0.25', '6.989999771', '0', '55', '6', '230', '728', '3798']
['8378563200', '2016-04-07', '9725', '7.710000038', '7.710000038', '2.253081083', '2.410000086', '0.529999971', '4.769999981', '0', '83', '11', '181', '670', '3839']
['8378563200', '2016-04-08', '8350', '6.619999886', '6.619999886', '2.092147112', '1.49000001', '0.529999971', '4.610000134', '0', '72', '10', '167', '868', '3713']
['8378563200', '2016-04-09', '2240', '1.779999971', '1.779999971', '0', '0', '0', '1.779999971', '0', '0', '0', '110', '843', '2606']
['8378563200', '2016-04-10', '2631', '2.089999914', '2.089999914', '0', '0', '0', '2.089999914', '0', '0', '0', '117', '727', '2624']
['8378563200', '2016-04-11', '8837', '7.010000229', '7.010000229', '2.092147112', '1.539999962', '0.879999995', '4.590000153', '0', '74', '17', '182', '811', '3775']
['8378563200', '2016-04-12', '3246', '2.569999933', '2.569999933', '2.253081083', '0.829999983', '0.709999979', '1.029999971', '0', '65', '15', '49', '243', '1882']
['8583815059', '2016-04-01', '2174', '1.700000048', '1.700000048', '0', '0', '0', '1.700000048', '0', '0', '0', '112', '1328', '2360']
['8583815059', '2016-04-02', '3494', '2.730000019', '2.730000019', '0', '0', '0', '2.690000057', '0', '0', '0', '166', '1274', '2517']
['8583815059', '2016-04-03', '2380', '1.860000014', '1.860000014', '0', '0', '0', '1.860000014', '0', '0', '0', '131', '1309', '2400']
['8583815059', '2016-04-04', '3159', '2.460000038', '2.460000038', '0', '0', '0', '2.460000038', '0', '0', '0', '147', '1293', '2462']
['8583815059', '2016-04-05', '6835', '5.329999924', '5.329999924', '0', '0.370000005', '0.730000019', '4.239999771', '0', '5', '15', '212', '1208', '2786']
['8583815059', '2016-04-06', '2098', '1.639999986', '1.639999986', '0', '0', '0', '1.629999995', '0', '0', '0', '112', '1328', '2354']
['8583815059', '2016-04-07', '2816', '2.200000048', '2.200000048', '0', '0', '0', '2.200000048', '0', '0', '0', '138', '1302', '2437']
['8583815059', '2016-04-08', '1408', '1.100000024', '1.100000024', '0', '0', '0', '1.100000024', '0', '0', '0', '79', '1052', '1814']
['8792009665', '2016-04-01', '4592', '2.940000057', '2.940000057', '0', '0.100000001', '0.140000001', '2.700000048', '0', '4', '8', '176', '748', '2260']
['8792009665', '2016-04-02', '8452', '5.409999847', '5.409999847', '0', '0.25999999', '0.389999986', '4.760000229', '0', '9', '24', '328', '1079', '3004']
['8792009665', '2016-04-03', '7238', '4.630000114', '4.630000114', '0', '0.109999999', '0.230000004', '4.289999962', '0', '2', '6', '279', '636', '2667']
['8792009665', '2016-04-04', '3821', '2.450000048', '2.450000048', '0', '0', '0.219999999', '2.230000019', '0', '0', '9', '161', '675', '2229']
['8792009665', '2016-04-05', '2332', '1.49000001', '1.49000001', '0', '0.01', '0.180000007', '1.299999952', '0', '1', '10', '111', '904', '2100']
['8792009665', '2016-04-06', '2121', '1.360000014', '1.360000014', '0', '0', '0', '1.360000014', '0', '0', '0', '122', '855', '2114']
['8792009665', '2016-04-07', '1291', '0.829999983', '0.829999983', '0', '0', '0', '0.829999983', '0', '0', '0', '77', '888', '1961']
['8792009665', '2016-04-08', '1467', '0.939999998', '0.939999998', '0', '0.100000001', '0.209999993', '0.629999995', '0', '2', '8', '71', '912', '1953']
['8792009665', '2016-04-09', '1022', '0.649999976', '0.649999976', '0', '0', '0', '0.649999976', '0', '0', '0', '63', '739', '1890']
['8792009665', '2016-04-10', '4605', '2.950000048', '2.950000048', '0', '0', '0', '2.950000048', '0', '0', '0', '179', '1261', '2253']
['8792009665', '2016-04-11', '178', '0.109999999', '0.109999999', '0', '0', '0', '0.109999999', '0', '0', '0', '12', '1428', '1725']
['8792009665', '2016-04-12', '20', '0.01', '0.01', '0', '0', '0', '0.01', '0', '0', '0', '6', '598', '728']
['8877689391', '2016-04-01', '18700', '15.81999969', '15.81999969', '0', '8.699999809', '0.159999996', '6.909999847', '0', '67', '3', '247', '1123', '3527']
['8877689391', '2016-04-02', '27572', '23.38999939', '23.38999939', '0', '14.72000027', '1.210000038', '7.340000153', '0.01', '116', '24', '260', '1040', '4220']
['8877689391', '2016-04-03', '15260', '8.18999958', '8.18999958', '0', '1.799999952', '0.75', '5.570000172', '0', '106', '17', '259', '1058', '3864']
['8877689391', '2016-04-04', '20779', '18.40999985', '18.40999985', '0', '11.72999954', '0.649999976', '6', '0', '78', '16', '208', '1138', '3662']
['8877689391', '2016-04-05', '10695', '8.119999886', '8.119999886', '0', '0.769999981', '0.180000007', '7.090000153', '0.01', '10', '3', '246', '1181', '2834']
['8877689391', '2016-04-06', '24136', '20.90999985', '20.90999985', '0', '12.22000027', '0.540000021', '8.079999924', '0', '87', '16', '318', '1019', '4039']
['8877689391', '2016-04-07', '10910', '8.420000076', '8.420000076', '0', '2.960000038', '0.389999986', '5.03000021', '0', '32', '11', '212', '1185', '2947']
['8877689391', '2016-04-08', '23014', '20.38999939', '20.38999939', '0', '11.10000038', '0.629999995', '8.619999886', '0', '70', '29', '359', '982', '4196']
['8877689391', '2016-04-09', '16470', '8.069999695', '8.069999695', '0', '0', '0.02', '8.020000458', '0', '90', '9', '289', '1052', '3841']
['8877689391', '2016-04-10', '28497', '27.53000069', '27.53000069', '0', '21.92000008', '1.120000005', '4.460000038', '0', '128', '46', '211', '1055', '4526']
['8877689391', '2016-04-11', '10622', '8.06000042', '8.06000042', '0', '1.470000029', '0.150000006', '6.369999886', '0.01', '18', '7', '225', '1190', '2820']
['8877689391', '2016-04-12', '2350', '1.779999971', '1.779999971', '0', '0', '0', '1.779999971', '0', '0', '0', '58', '531', '938']
All Data Uploaded

In [14]:
## read data in pandas
df = pd.read_csv('FitBit_data.csv')
df.head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,2016-03-25,11004,7.11,7.11,0.0,2.57,0.46,4.07,0.0,33,12,205,804,1819
1,1503960366,2016-03-26,17609,11.55,11.55,0.0,6.92,0.73,3.91,0.0,89,17,274,588,2154
2,1503960366,2016-03-27,12736,8.53,8.53,0.0,4.66,0.16,3.71,0.0,56,5,268,605,1944
3,1503960366,2016-03-28,13231,8.93,8.93,0.0,3.19,0.79,4.95,0.0,39,20,224,1080,1932
4,1503960366,2016-03-29,12041,7.85,7.85,0.0,2.16,1.09,4.61,0.0,28,28,243,763,1886

###### 3. convert all the dates avaible in dataset to timestamp format in pandas and in sql you to convert it in date format

In [15]:
df['ActivityDate'] = pd.to_datetime(df['ActivityDate'],format='%Y-%m-%d %H:%M:%S')

In [16]:
df['ActivityDate'].dtype

dtype('<M8[ns]')

In [17]:
df.head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,2016-03-25,11004,7.11,7.11,0.0,2.57,0.46,4.07,0.0,33,12,205,804,1819
1,1503960366,2016-03-26,17609,11.55,11.55,0.0,6.92,0.73,3.91,0.0,89,17,274,588,2154
2,1503960366,2016-03-27,12736,8.53,8.53,0.0,4.66,0.16,3.71,0.0,56,5,268,605,1944
3,1503960366,2016-03-28,13231,8.93,8.93,0.0,3.19,0.79,4.95,0.0,39,20,224,1080,1932
4,1503960366,2016-03-29,12041,7.85,7.85,0.0,2.16,1.09,4.61,0.0,28,28,243,763,1886

In [18]:
df['ActivityDate'].head()

0   2016-03-25
1   2016-03-26
2   2016-03-27
3   2016-03-28
4   2016-03-29
Name: ActivityDate, dtype: datetime64[ns]

###### Find out in this data that how many unique id's we have

In [19]:
df['Id'].unique()

array([1503960366, 1624580081, 1644430081, 1844505072, 1927972279,
       2022484408, 2026352035, 2320127002, 2347167796, 2873212765,
       2891001357, 3372868164, 3977333714, 4020332650, 4057192912,
       4319703577, 4388161847, 4445114986, 4558609924, 4702921684,
       5553957443, 5577150313, 6117666160, 6290855005, 6391747486,
       6775888955, 6962181067, 7007744171, 7086361926, 8053475328,
       8253242879, 8378563200, 8583815059, 8792009665, 8877689391],
      dtype=int64)

In [20]:
len(df['Id'].unique())

35

35 unique ids

##### 5. which id is one of the active id that you have in whole dataset

In [24]:
df['Id'].value_counts().sort_values(ascending=False).head(4)

4057192912    32
4020332650    32
1624580081    19
1503960366    19
Name: Id, dtype: int64

###### 6. how many of them have not logged there activity find out in terms of number of ids

In [25]:
df.head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,2016-03-25,11004,7.11,7.11,0.0,2.57,0.46,4.07,0.0,33,12,205,804,1819
1,1503960366,2016-03-26,17609,11.55,11.55,0.0,6.92,0.73,3.91,0.0,89,17,274,588,2154
2,1503960366,2016-03-27,12736,8.53,8.53,0.0,4.66,0.16,3.71,0.0,56,5,268,605,1944
3,1503960366,2016-03-28,13231,8.93,8.93,0.0,3.19,0.79,4.95,0.0,39,20,224,1080,1932
4,1503960366,2016-03-29,12041,7.85,7.85,0.0,2.16,1.09,4.61,0.0,28,28,243,763,1886

In [27]:
df['Id'][df['LoggedActivitiesDistance'] == 0].unique()

array([1503960366, 1624580081, 1644430081, 1844505072, 1927972279,
       2022484408, 2026352035, 2320127002, 2347167796, 2873212765,
       2891001357, 3372868164, 3977333714, 4020332650, 4057192912,
       4319703577, 4388161847, 4445114986, 4558609924, 4702921684,
       5553957443, 5577150313, 6117666160, 6290855005, 6391747486,
       6775888955, 6962181067, 7007744171, 7086361926, 8053475328,
       8253242879, 8378563200, 8583815059, 8792009665, 8877689391],
      dtype=int64)

In [28]:
len(df['Id'][df['LoggedActivitiesDistance'] == 0].unique())

35

###### 7. Find out who is the laziest person id that we have in dataset

In [30]:
df.groupby('Id')['TotalDistance'].sum().sort_values(ascending=True).head(1)

Id
4388161847    0.0
Name: TotalDistance, dtype: float64

###### 8. Explore over an internet that how much calories burn is required for a healthy person and find out how many healthy person we have in our dataset

In [33]:
## on an average 2000 to 2500 calories should be burned
df_cal = df.groupby('Id')['Calories'].mean()
df_cal[df_cal >= 2000].count()

20

###### 9. how many person are not a regular person with respect to activity try to find out those

In [38]:
### A perosn is regular if he is active for atleast 14 days
df_active = df.groupby('Id')['ActivityDate'].count()
df_active[df_active >= 14].count()

8

###### 10. who is the thired most active person in this dataset find out those in pandas and in sql both

In [53]:
df_third_active = pd.DataFrame(df.groupby('Id')['ActivityDate'].count().sort_values(ascending=False))
df_third_active.iloc[2]

ActivityDate    19
Name: 1503960366, dtype: int64

###### 11. who is the 5th most laziest person avilable in dataset find it out

In [56]:
df_lazy = pd.DataFrame(df.groupby('Id')['TotalDistance'].sum().sort_values(ascending=True))
df_lazy.iloc[4]

TotalDistance    18.13
Name: 1927972279, dtype: float64

###### 12. what is a totla acumulative calories burn for a person find out

In [59]:
df.groupby('Id')['Calories'].cumsum()

0       1819
1       3973
2       5917
3       7849
4       9735
       ...
452    29289
453    33130
454    37656
455    40476
456    41414
Name: Calories, Length: 457, dtype: int64